enum FilesActionType {
    GET_FILES_REQUEST = 'GET_FILES_REQUEST',
    GET_FILES_SUCCESS = 'GET_FILES_SUCCESS',
    GET_FILES_FAILED = 'GET_FILES_FAILED',
    POST_FILES_REQUEST = 'POST_FILES_REQUEST',
    POST_FILES_SUCCESS = 'POST_FILES_SUCCESS',
    POST_FILES_FAILED = 'POST_FILES_FAILED',
}

export default FilesActionType